In [5]:

import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

df.head()


sepal length  sepal width  petal length  petal width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:


#Standardize the Data
from sklearn.preprocessing import StandardScaler


features = ['sepal length', 'sepal width', 'petal length', 'petal width']

#separating
x= df.loc[:,features].values

y= df.loc[:,'target'].values

x=StandardScaler().fit_transform(x)

pd.DataFrame(x).describe()




0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -2.775558e-16 -5.140333e-16  1.154632e-16  9.251859e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00

In [7]:
x.shape


(150, 4)

In [8]:

from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
principalComponents = pca.fit_transform(x)
principalDF = pd.DataFrame(data=principalComponents, columns = ['principal component 1', 'principal component 2'])

principalDF.shape



(150, 2)

In [9]:

finalDf = pd.concat([principalDF, df[['target']]], axis = 1)
finalDf


principal component 1  principal component 2          target
0                -2.264542               0.505704     Iris-setosa
1                -2.086426              -0.655405     Iris-setosa
2                -2.367950              -0.318477     Iris-setosa
3                -2.304197              -0.575368     Iris-setosa
4                -2.388777               0.674767     Iris-setosa
5                -2.070537               1.518549     Iris-setosa
6                -2.445711               0.074563     Iris-setosa
7                -2.233842               0.247614     Iris-setosa
8                -2.341958              -1.095146     Iris-setosa
9                -2.188676              -0.448629     Iris-setosa
10               -2.163487               1.070596     Iris-setosa
11               -2.327378               0.158587     Iris-setosa
12               -2.224083              -0.709118     Iris-setosa
13               -2.639716              -0.938282     Iris-setosa
14               -2.192292               1.889979     Iris-setosa
15               -2.251465               2.722371     Iris-setosa
16               -2.202750               1.513750     Iris-setosa
17               -2.190179               0.514304     Iris-setosa
18               -1.894074               1.431111     Iris-setosa
19               -2.339949               1.158033     Iris-setosa
20               -1.914556               0.430465     Iris-setosa
21               -2.204645               0.952457     Iris-setosa
22               -2.774170               0.489517     Iris-setosa
23               -1.820412               0.106751     Iris-setosa
24               -2.228217               0.162186     Iris-setosa
25               -1.957024              -0.607893     Iris-setosa
26               -2.052063               0.266014     Iris-setosa
27               -2.168194               0.552016     Iris-setosa
28               -2.140306               0.336640     Iris-setosa
29               -2.268790              -0.314879     Iris-setosa
..                     ...                    ...             ...
120               2.040496               0.907399  Iris-virginica
121               0.973915              -0.571174  Iris-virginica
122               2.898064               0.397791  Iris-virginica
123               1.329194              -0.486761  Iris-virginica
124               1.704241               1.014148  Iris-virginica
125               1.957728               1.003335  Iris-virginica
126               1.171905              -0.318897  Iris-virginica
127               1.019781               0.065543  Iris-virginica
128               1.786009              -0.193273  Iris-virginica
129               1.864778               0.555382  Iris-virginica
130               2.435497               0.246654  Iris-virginica
131               2.316082               2.626184  Iris-virginica
132               1.860371              -0.184672  Iris-virginica
133               1.111272              -0.295986  Iris-virginica
134               1.197469              -0.817168  Iris-virginica
135               2.800949               0.844748  Iris-virginica
136               1.580155               1.072474  Iris-virginica
137               1.347044               0.422256  Iris-virginica
138               0.923433               0.019230  Iris-virginica
139               1.853552               0.672423  Iris-virginica
140               2.016157               0.610397  Iris-virginica
141               1.903117               0.686025  Iris-virginica
142               1.153190              -0.701326  Iris-virginica
143               2.043308               0.864685  Iris-virginica
144               2.001691               1.048550  Iris-virginica
145               1.870522               0.382822  Iris-virginica
146               1.558492              -0.905314  Iris-virginica
147               1.520845               0.266795  Iris-virginica
148               1.376391               1.01

In [10]:


# information (variance) can be attributed to each of the principal components
# when reducing dimension, you lose some of the variance 
# by using the attribute explained_variance_ration_,you can see that the first principal component contains 72.77% of the variance and the second principal component contains 23.03% of the variance. Together, the two components contain 95.80% of the information.


pca.explained_variance_ratio_



array([ 0.72770452,  0.23030523])

In [11]:

pca.explained_variance_ratio_.sum()


0.95800975361481988

In [12]:


# Example

import pandas as pd

df = pd.read_csv(
    filepath_or_buffer='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
    header=None, 
    sep=',')

df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']


In [13]:
#  drops the empty line at file-end
df.dropna(how="all", inplace=True)
df.isnull().sum()

sepal_len    0
sepal_wid    0
petal_len    0
petal_wid    0
class        0
dtype: int64

In [14]:


# split data table into data X and class labels y
# to ndarray
X=df.iloc[:,0:4].values
y=df.iloc[:,4].values


In [15]:

from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

X_std.shape

(150, 4)

In [16]:

# Eigndecompoosition 
# Computing Eigenvectors and Eigenvalues

# Covariance Matrix
# the classic approach to PCA is to perform the eigndecomposition on the covariance matrix


In [17]:

import numpy as np
mean_vec = np.mean(X_std, axis = 0)

cov_mat = (X_std - mean_vec).T.dot((X_std-mean_vec))/(X_std.shape[0]-1)

print('Covariance matrix \n%s' %cov_mat)



Covariance matrix 
[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]


In [18]:


#another approach iis just to use numpy cov function
print('Numpy Covariance Matrix: \n%s'%np.cov(X_std.T))




Numpy Covariance Matrix: 
[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]


In [19]:

# Next, we perform an eigen decomposition on the covariance matrix

cov_mat = np.cov(X_std.T)
eig_vals , eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)



Eigenvectors 
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]

Eigenvalues 
[ 2.93035378  0.92740362  0.14834223  0.02074601]


In [20]:

# Correlation Matrix

# . Eigendecomposition of the standardized data based on the correlation matrix:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)




Eigenvectors 
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]

Eigenvalues 
[ 2.91081808  0.92122093  0.14735328  0.02060771]


In [21]:

#Eigendecomposition of the raw data based on the correlation matrix:


cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)


Eigenvectors 
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]

Eigenvalues 
[ 2.91081808  0.92122093  0.14735328  0.02060771]


In [22]:


# Make a list of (eignvalue, eignvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i 
            in range(len(eig_vals))]


# sort the (eigenvalue, eigenvector) tuples from high to low

eig_pairs.sort()
eig_pairs.reverse()


In [23]:


print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])



Eigenvalues in descending order:
2.91081808375
0.921220930707
0.147353278305
0.0206077072356


In [24]:

tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

print(cum_var_exp)



[  72.77045209   95.80097536   99.48480732  100.        ]


In [28]:

import numpy as np

matrix_W = np.hstack((eig_pairs[0][1].reshape(4,1), 
                      eig_pairs[1][1].reshape(4,1)))

print('Matrix W:\n', matrix_W)



Matrix W:
 [[ 0.52237162 -0.37231836]
 [-0.26335492 -0.92555649]
 [ 0.58125401 -0.02109478]
 [ 0.56561105 -0.06541577]]


In [38]:

from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components = 2)
Y_sklearn = sklearn_pca.fit_transform(X_std)

print(Y_sklearn.shape)


(150, 2)
